### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rubberkitten** [Raphire/Win11Debloat#12]
Ran the Windows 11 debloat and it crashed my desktop and my bitdefender said it was a virus and made my screen black but my youtube video is still up playing. I cant access my desktop so i have to force restart the computer. Instead of debloating, it fucked windows os. Need to fix your exe file bruh.

**Comment by Raphire** [comment]
Heya,

Sorry to hear you ran into issues. Luckily from your description it seems like it was a simple case of Windows Explorer not recovering properly.

Win11Debloat automatically restarts Windows Explorer process to apply changes. The desktop is a part of that process and will restart too. Normally this should just take a second, but I'm guessing Bitdefender intervened and stopped Windows Explorer from starting back up properly.

To be clear: This doesn't do any damage or break any part of the OS. The desktop simply remained black because the windows explorer process that's responsible for it wasn't running anymore. 

Did you run into any issues after restarting Windows?

**Comment by Rubberkitten** [comment]
I logged out from ctrl, alt, del and back in and it was fine. Im trying to
get rid of ms edge. I am unable to run the debloat anymore. Just like the
other debloats, they just pop up like a blip and close.

**Comment by Raphire** [comment]
I'm guessing bitdefender is blocking scripts from executing, that would explain why they immediately close.

Win11Debloat cannot remove microsoft edge, Microsoft makes it hard to do and, in my opinion, it's more trouble than it's worth. Especially for the average user.

I would suggest looking up a guide to do it manually if you really want it gone.
