### ISSUE TITLE
DISM no longer works, and windows extremly slow after applying this default

### ISSUE THREAD

**Issue by Elrinth** [Raphire/Win11Debloat#125]
**Describe the bug**
Running "DISM /Online /Cleanup-Image /CheckHealth" goes too fast

**To Reproduce**
1. Run this debloat script
2. Reboot computer
3. Run first sfc /scannow
4. Then run "DISM /Online /Cleanup-Image /CheckHealth".. It finishes so fast, it's obvious it doesn't do anything.

**Expected behavior**
It should compare itself to microsofts servers and take a little while to finish.

**Screenshots**

**Additional context**

**Comment by Elrinth** [comment]
sfc /scannow made my computer go better again fyi

**Comment by Raphire** [comment]
> sfc /scannow made my computer run as normal again fyi

Heya, Glad the slowdown was fixed.

As for DISM, this does seem to work ok on my system and VMs. It works as expected before and after running the script. I think the problem lies in that fact that you need to first scan your image by running
```
DISM /Online /Cleanup-Image /ScanHealth
```
And then run
```
DISM /Online /Cleanup-Image /CheckHealth
```
See documentation here: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/repair-a-windows-image
