### ISSUE TITLE
(google translator translation)  Microsoft store not working (win11)

### ISSUE THREAD

**Issue by S4KITYZ** [Raphire/Win11Debloat#157]
after i used the command, the Microsoft Store just stopped working
![imagem_2024-11-18_155743914](https://github.com/user-attachments/assets/8c942127-97ac-4bbb-a5e0-5b7ddc57d7aa)

**Comment by Raphire** [comment]
Heya,

The issue seems to be related to an update service being disabled. This page has some troubleshooting steps that may help: https://www.windowsdigitals.com/microsoft-store-one-of-the-update-services-is-not-running-properly/

Win11Debloat doesn't disable any update services, did you use any other tools?

**Comment by Raphire** [comment]
Closed due to lack of information - Issue seems to be unrelated to the script.
