### ISSUE TITLE
More Bloat To Remove

### ISSUE THREAD

**Issue by savantes1** [Raphire/Win11Debloat#16]
Thank you for building and maintaining this wonderful script. I'm setting up some new Windows 11 machines for my family and have been astonished with just how much bloat Windows now has preinstalled. This script has already saved me **HOURS** of configuration so, again, bless you :)

I just wanted to bring to your attention that after doing a fresh install of Windows 11 and running your script I still have links to the following apps in the start menu under the "Pinned" heading:

* Spotify
* WhatsApp
* LinkedIn
* Outlook

I don't think these apps are actually installed by default, but the links (bloat) are put there by default. Was hoping maybe the script could be updated to remove these types of unwanted links along with all of the other bloat it removes.

Thanks again for the awesome script!

**Comment by Raphire** [comment]
Heya,

First of, glad to hear this script has been helpful to you!

I share your pain with the pinned apps in the start menu, it's a difficult problem to tackle, because the pinned apps are stored in a binary file that can't really be edited.

The script does however have an option to completely clear all pinned apps in the startmenu by completely replacing the binary file. This option is available when you select custom setup when you run the script. I hope that works for you!
