### ISSUE TITLE
Support of audit environment

### ISSUE THREAD

**Issue by LuCarhub** [Raphire/Win11Debloat#31]
Hi Raphine,

very nice work your script. I've used it on 3 or 4 different new installation of windows 11 to create an image with sysprep. It seems that it works well removing unuseful ms store app, but it loses personalization of interface (position of start button, combining of button in the taskbar). Did you try to use it in audit mode?

**Comment by Raphire** [comment]
Heya,

Just to avoid any miscommunication: From what I understand you're running the Win11Debloat script in audit mode to prep a Windows 11 image.

I have not personally used or tested audit mode, but the reason I think certain changes are not applying when running the script in audit mode is because some changes that the script makes only apply the user profile of the user that executes the script. The reason that app removal does work is because the apps are removed from the image itself.

Unfortunately the only (supported) way to apply many of the personalization changes on a global level is through GPO/intune.

**Comment by Raphire** [comment]
Ah I see! I was able to find more information, and it does seem like something worth implementing into Win11Debloat. I unfortunately also do not have much time right now, but I'll try keep this thread up to date.

**Comment by DruidCtba** [comment]
Hey guys, I'm not sure where to ask, I'm new here on github, but please, how can I know if any Windows update, the KB's of life, DID NOT BRING BACK THE TELEMETRY OR OTHER STUFF THAT THIS SCRIPT MIGHT HAVE REMOVED / DISABLED, I ask because I imagine the guys at Microsoft are not so naive as to not know about these Debloats, so my question is - is there a way for me to run a script or some program that checks for me if Microsoft didn't bring back these telemetries among other things that were disabled by this debloat?

Thanks for everyone's attention and sorry if I'm asking in the wrong place.

Cheers,

Druid®.

**Comment by loadstring1** [comment]
> Microsoft are not so naive as to not know about these Debloats, so my question is - is there a way for me to run a script or some program that checks for me if Microsoft didn't bring back these telemetries among other things that were disabled by this debloat?

if you disable windows updates thats enough to prevent microsoft from reinstalling bloat and re-enabling telemetry and spyware

**Comment by johnnyq** [comment]
Hey checking in on this one as this can prove to be very useful and thank you for this great script

**Comment by Raphire** [comment]
Heya

I'm happy to report the sysprep feature is in the works. I have opened a new branch to open it up to testing. Please be advised that this may contain a few bugs. I have personally noticed that Windows doesn't respect the Search button setting here.

If you wish to test it out, you can find it here: https://github.com/Raphire/Win11Debloat/tree/Sysprep-experimental

**Comment by Raphire** [comment]
This feature has been added as of [1d2c6ea](https://github.com/Raphire/Win11Debloat/commit/1d2c6eaba050ed8ec289d6d9c635a47671f5d59a). 

To run the script in Sysprep mode simply use the -Sysprep parameter while executing the script. All changes will be applied to the Windows default user template, and affect all user accounts created thereafter.

**Comment by johnnyq** [comment]
Excellent Work @Raphire Will this also work if Im creating an initial admin user and apply the script with -Sysprep to that user will it affect all users created after that or do i have to use sysprep?

**Comment by Raphire** [comment]
> Excellent Work @Raphire Will this also work if Im creating an initial admin user and apply the script with -Sysprep to that user will it affect all users created after that or do i have to use sysprep audit mode?

When you run the script with Sysprep the changes are applied to the default user template instead of the current user. 

So ideally you would run the script in audit mode before creating the initial admin account. Alternatively you can run the script twice, once with and once without the Sysprep parameter.
