### ISSUE TITLE
i get this gamingbar thing popup when playing minecraft

### ISSUE THREAD

**Issue by Strealstud** [Raphire/Win11Debloat#80]
When i hit windows key and g or i open a app after debloating i get youll neeed a new app to open this ms_gamingoverlay link

To reproduce open up a game or hit windows key and g

when you click anywhere the popup closes

![IMG_3600](https://github.com/Raphire/Win11Debloat/assets/127317814/ede4fbe6-cea5-462a-a21d-995f6165af6d)

**Comment by Raphire** [comment]
Heya,

This is very annoying for sure. 

I believe this can be fixed by disabling a feature called Game DVR. For some reason Microsoft doesn't do this automatically after the gaming overlay is uninstalled.

You can disable this feature via Win11Debloat by running it with the `-DisableDVR` parameter.

To do this simply paste this into powershell: 
```& ([scriptblock]::Create((irm "https://raw.githubusercontent.com/Raphire/Win11Debloat/master/Get.ps1"))) -DisableDVR```

Please let me know if this works for you

**Comment by Strealstud** [comment]
Will try


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Strealstud** [comment]
yep it worked
i think

**Comment by Raphire** [comment]
Thanks for confirming! Closing issue
