### ISSUE TITLE
Error: Unable to uninstall Microsoft Edge via Winget

### ISSUE THREAD

**Issue by levdopa** [Raphire/Win11Debloat#97]
I ran the script in an admin power shell like this
& ([scriptblock]::Create((irm "https://win11debloat.raphi.re/")))

and I get the message: Error: Unable to uninstall Microsoft Edge via Winget

**Comment by Raphire** [comment]
Heya,

This error occurs because uninstalling Edge via winget is doesn't work for users outside of the EEA (European Economic Area). If this error occurs it should offer you the option to uninstall edge forcefully, although that option isn't recommended for most users as it can have unintended side-effects.

**Comment by levdopa** [comment]
ok thanks, im in usa
